//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relacion.Producto", Namespace="http://schemas.datacontract.org/2004/07/WebApplication7.Web.clases")]
    [System.SerializableAttribute()]
    public partial class RelacionProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relacion.Cliente", Namespace="http://schemas.datacontract.org/2004/07/WebApplication7.Web.clases")]
    [System.SerializableAttribute()]
    public partial class RelacionCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMiServicio")]
    public interface IMiServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/CrearProducto", ReplyAction="http://tempuri.org/IMiServicio/CrearProductoResponse")]
        void CrearProducto(string nombre, decimal precio, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/CrearProducto", ReplyAction="http://tempuri.org/IMiServicio/CrearProductoResponse")]
        System.Threading.Tasks.Task CrearProductoAsync(string nombre, decimal precio, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ObtenerProductos", ReplyAction="http://tempuri.org/IMiServicio/ObtenerProductosResponse")]
        WebApplication7.ServiceReference1.RelacionProducto[] ObtenerProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ObtenerProductos", ReplyAction="http://tempuri.org/IMiServicio/ObtenerProductosResponse")]
        System.Threading.Tasks.Task<WebApplication7.ServiceReference1.RelacionProducto[]> ObtenerProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ObtenerProductoPorID", ReplyAction="http://tempuri.org/IMiServicio/ObtenerProductoPorIDResponse")]
        WebApplication7.ServiceReference1.RelacionProducto ObtenerProductoPorID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ObtenerProductoPorID", ReplyAction="http://tempuri.org/IMiServicio/ObtenerProductoPorIDResponse")]
        System.Threading.Tasks.Task<WebApplication7.ServiceReference1.RelacionProducto> ObtenerProductoPorIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ActualizarProducto", ReplyAction="http://tempuri.org/IMiServicio/ActualizarProductoResponse")]
        void ActualizarProducto(int id, string nombre, decimal precio, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ActualizarProducto", ReplyAction="http://tempuri.org/IMiServicio/ActualizarProductoResponse")]
        System.Threading.Tasks.Task ActualizarProductoAsync(int id, string nombre, decimal precio, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/EliminarProducto", ReplyAction="http://tempuri.org/IMiServicio/EliminarProductoResponse")]
        void EliminarProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/EliminarProducto", ReplyAction="http://tempuri.org/IMiServicio/EliminarProductoResponse")]
        System.Threading.Tasks.Task EliminarProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/CrearCliente", ReplyAction="http://tempuri.org/IMiServicio/CrearClienteResponse")]
        void CrearCliente(string nombre, string apellido, string email, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/CrearCliente", ReplyAction="http://tempuri.org/IMiServicio/CrearClienteResponse")]
        System.Threading.Tasks.Task CrearClienteAsync(string nombre, string apellido, string email, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ObtenerClientes", ReplyAction="http://tempuri.org/IMiServicio/ObtenerClientesResponse")]
        WebApplication7.ServiceReference1.RelacionCliente[] ObtenerClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/ObtenerClientes", ReplyAction="http://tempuri.org/IMiServicio/ObtenerClientesResponse")]
        System.Threading.Tasks.Task<WebApplication7.ServiceReference1.RelacionCliente[]> ObtenerClientesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiServicioChannel : WebApplication7.ServiceReference1.IMiServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioClient : System.ServiceModel.ClientBase<WebApplication7.ServiceReference1.IMiServicio>, WebApplication7.ServiceReference1.IMiServicio {
        
        public MiServicioClient() {
        }
        
        public MiServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CrearProducto(string nombre, decimal precio, string descripcion) {
            base.Channel.CrearProducto(nombre, precio, descripcion);
        }
        
        public System.Threading.Tasks.Task CrearProductoAsync(string nombre, decimal precio, string descripcion) {
            return base.Channel.CrearProductoAsync(nombre, precio, descripcion);
        }
        
        public WebApplication7.ServiceReference1.RelacionProducto[] ObtenerProductos() {
            return base.Channel.ObtenerProductos();
        }
        
        public System.Threading.Tasks.Task<WebApplication7.ServiceReference1.RelacionProducto[]> ObtenerProductosAsync() {
            return base.Channel.ObtenerProductosAsync();
        }
        
        public WebApplication7.ServiceReference1.RelacionProducto ObtenerProductoPorID(int id) {
            return base.Channel.ObtenerProductoPorID(id);
        }
        
        public System.Threading.Tasks.Task<WebApplication7.ServiceReference1.RelacionProducto> ObtenerProductoPorIDAsync(int id) {
            return base.Channel.ObtenerProductoPorIDAsync(id);
        }
        
        public void ActualizarProducto(int id, string nombre, decimal precio, string descripcion) {
            base.Channel.ActualizarProducto(id, nombre, precio, descripcion);
        }
        
        public System.Threading.Tasks.Task ActualizarProductoAsync(int id, string nombre, decimal precio, string descripcion) {
            return base.Channel.ActualizarProductoAsync(id, nombre, precio, descripcion);
        }
        
        public void EliminarProducto(int id) {
            base.Channel.EliminarProducto(id);
        }
        
        public System.Threading.Tasks.Task EliminarProductoAsync(int id) {
            return base.Channel.EliminarProductoAsync(id);
        }
        
        public void CrearCliente(string nombre, string apellido, string email, string telefono) {
            base.Channel.CrearCliente(nombre, apellido, email, telefono);
        }
        
        public System.Threading.Tasks.Task CrearClienteAsync(string nombre, string apellido, string email, string telefono) {
            return base.Channel.CrearClienteAsync(nombre, apellido, email, telefono);
        }
        
        public WebApplication7.ServiceReference1.RelacionCliente[] ObtenerClientes() {
            return base.Channel.ObtenerClientes();
        }
        
        public System.Threading.Tasks.Task<WebApplication7.ServiceReference1.RelacionCliente[]> ObtenerClientesAsync() {
            return base.Channel.ObtenerClientesAsync();
        }
    }
}
